# Generated by Django 3.1.3 on 2020-12-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_delete_filter'),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='id',
        ),
        migrations.RemoveField(
            model_name='action',
            name='verb',
        ),
        migrations.AddField(
            model_name='action',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.post'),
            preserve_default=False,
        ),
    ]
